### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "prasant hero",
  "email": "hero@moto.com",
  "address": "nagpur, india",
  "dateOfBirth": "2001-07-03",
  "registeredDate": "2025-08-17"
}

###