### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "lexy high",
  "email": "lexy@sbjit.com",
  "address": "nagpur, india",
  "dateOfBirth": "2005-07-03",
  "registeredDate": "2026-08-17"
}

###